"""``db upgrade | current | revision`` — database schema migrations (Alembic)."""

from __future__ import annotations

import typer

from app.cli._common import console, friendly

db_app = typer.Typer(no_args_is_help=True)


@db_app.command("upgrade")
@friendly
def upgrade(
    revision: str = typer.Option("head", "--revision", "-r", help="Target revision (default: latest)."),
) -> None:
    """Apply migrations up to REVISION (creates the database when it does not exist)."""
    from app.core.settings import get_settings
    from app.db.migrate import current_revision, upgrade_db

    upgrade_db(revision=revision)
    console.print(f"database [bold]{_safe_url(get_settings().db_url)}[/] at revision {current_revision()}")


@db_app.command("current")
@friendly
def current() -> None:
    """Show the database's current revision."""
    from app.core.settings import get_settings
    from app.db.migrate import current_revision

    rev = current_revision()
    console.print(f"{_safe_url(get_settings().db_url)}: {rev or 'no schema (run `db upgrade`)'}")


@db_app.command("revision")
@friendly
def revision(
    message: str = typer.Option(..., "--message", "-m", help="Revision message."),
    empty: bool = typer.Option(False, "--empty", help="Create an empty revision (no autogenerate)."),
) -> None:
    """Create a migration revision (autogenerated from the models against an up-to-date database)."""
    from app.db.migrate import make_revision

    make_revision(message, autogenerate=not empty)
    console.print(f"revision created: {message}")


def _safe_url(url: str) -> str:
    if "@" in url and "://" in url:
        scheme, rest = url.split("://", 1)
        creds, host = rest.rsplit("@", 1)
        return f"{scheme}://{creds.split(':', 1)[0]}:***@{host}"
    return url
