"""local elections: water boards, election province, race details

Schema for the in-between local elections (docs/LOCAL_ELECTIONS.md): the ``water_board`` table
(REAL water authority areas) with ``geo_unit.water_board_id``, ``election.province_id`` (a local
election belongs to one province and date) and ``race.threshold`` / ``race.details_json`` (Yes/No
thresholds and contest data).  Autogenerated from ``app.models`` and reviewed by hand.

Revision ID: 572107020ab6
Revises: d4bc2f767e86
Create Date: 2026-10-09 08:09:53.225102
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "572107020ab6"
down_revision: str | None = "d4bc2f767e86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "water_board",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vintage_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("area_km2", sa.Float(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_water_board_province_id_province")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_source.id"], name=op.f("fk_water_board_source_id_data_source")
        ),
        sa.ForeignKeyConstraint(
            ["vintage_id"], ["geo_vintage.id"], name=op.f("fk_water_board_vintage_id_geo_vintage")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_water_board")),
        sa.UniqueConstraint("vintage_id", "code", name=op.f("uq_water_board_vintage_id_code")),
    )
    with op.batch_alter_table("water_board", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_water_board_vintage_id"), ["vintage_id"], unique=False)

    with op.batch_alter_table("election", schema=None) as batch_op:
        batch_op.add_column(sa.Column("province_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_election_province_id"), ["province_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_election_province_id_province"), "province", ["province_id"], ["id"]
        )

    with op.batch_alter_table("geo_unit", schema=None) as batch_op:
        batch_op.add_column(sa.Column("water_board_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_geo_unit_water_board_id"), ["water_board_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_geo_unit_water_board_id_water_board"), "water_board", ["water_board_id"], ["id"]
        )

    with op.batch_alter_table("race", schema=None) as batch_op:
        batch_op.add_column(sa.Column("threshold", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("details_json", sa.Text(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("race", schema=None) as batch_op:
        batch_op.drop_column("details_json")
        batch_op.drop_column("threshold")

    with op.batch_alter_table("geo_unit", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_geo_unit_water_board_id_water_board"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_geo_unit_water_board_id"))
        batch_op.drop_column("water_board_id")

    with op.batch_alter_table("election", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_election_province_id_province"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_election_province_id"))
        batch_op.drop_column("province_id")

    with op.batch_alter_table("water_board", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_water_board_vintage_id"))

    op.drop_table("water_board")
