"""initial schema

The complete schema of the NL Federal Election Simulator (55 tables; see docs/DATABASE.md),
autogenerated from ``app.models`` against an empty database and reviewed by hand.

The only reference cycle (``race.winner_ballot_candidate_id`` → ``ballot_candidate`` while
``ballot_candidate.race_id`` → ``race``) is created inline on SQLite (which accepts forward
references) and as a separate ``ALTER TABLE`` once both tables exist elsewhere (PostgreSQL); the
downgrade clears and drops it before ``ballot_candidate`` so the tables can be removed in order.

Revision ID: d4bc2f767e86
Revises:
Create Date: 2026-09-24 17:19:47.277672
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "d4bc2f767e86"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_RACE_WINNER_FK = "fk_race_winner_ballot_candidate"


def _is_sqlite() -> bool:
    return op.get_context().dialect.name == "sqlite"


def upgrade() -> None:
    sqlite = _is_sqlite()
    # ### commands auto generated by Alembic, reviewed (race ↔ ballot_candidate cycle) ###
    op.create_table(
        "app_meta",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_meta")),
    )
    op.create_table(
        "data_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("publisher", sa.String(length=120), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("license", sa.String(length=80), nullable=False),
        sa.Column("data_category", sa.String(length=16), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_source")),
        sa.UniqueConstraint("key", name=op.f("uq_data_source_key")),
    )
    op.create_table(
        "party",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("abbreviation", sa.String(length=16), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=False),
        sa.Column("color_secondary", sa.String(length=9), nullable=True),
        sa.Column("family", sa.String(length=40), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ideology_economic", sa.Float(), nullable=False),
        sa.Column("ideology_social", sa.Float(), nullable=False),
        sa.Column("ideology_europe", sa.Float(), nullable=False),
        sa.Column("base_support", sa.Float(), nullable=False),
        sa.Column("turnout_propensity", sa.Float(), nullable=False),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("dissolved_year", sa.Integer(), nullable=True),
        sa.Column("successor_party_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["successor_party_id"], ["party.id"], name=op.f("fk_party_successor_party_id_party")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_party")),
        sa.UniqueConstraint("code", name=op.f("uq_party_code")),
    )
    op.create_table(
        "pollster",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("rating_label", sa.String(length=8), nullable=True),
        sa.Column("default_method", sa.String(length=24), nullable=True),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pollster")),
        sa.UniqueConstraint("name", name=op.f("uq_pollster_name")),
    )
    op.create_table(
        "province",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("cbs_code", sa.String(length=4), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("name_en", sa.String(length=60), nullable=True),
        sa.Column("capital", sa.String(length=60), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_province")),
        sa.UniqueConstraint("cbs_code", name=op.f("uq_province_cbs_code")),
        sa.UniqueConstraint("code", name=op.f("uq_province_code")),
        sa.UniqueConstraint("name", name=op.f("uq_province_name")),
    )
    op.create_table(
        "scenario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("document", sa.Text(), nullable=False),
        sa.Column("document_hash", sa.String(length=16), nullable=False),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["scenario.id"], name=op.f("fk_scenario_parent_id_scenario")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario")),
        sa.UniqueConstraint("slug", name=op.f("uq_scenario_slug")),
    )
    op.create_table(
        "candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("first_name", sa.String(length=60), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("gender", sa.String(length=8), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("home_municipality_code", sa.String(length=6), nullable=True),
        sa.Column("home_province_id", sa.Integer(), nullable=True),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("ideology_economic", sa.Float(), nullable=False),
        sa.Column("ideology_social", sa.Float(), nullable=False),
        sa.Column("quality", sa.Float(), nullable=False),
        sa.Column("campaign_strength", sa.Float(), nullable=False),
        sa.Column("fundraising", sa.Float(), nullable=False),
        sa.Column("favorability", sa.Float(), nullable=True),
        sa.Column("approval", sa.Float(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("portrait_key", sa.String(length=40), nullable=True),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["home_province_id"], ["province.id"], name=op.f("fk_candidate_home_province_id_province")
        ),
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], name=op.f("fk_candidate_party_id_party")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate")),
        sa.UniqueConstraint("key", name=op.f("uq_candidate_key")),
    )
    with op.batch_alter_table("candidate", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_candidate_full_name"), ["full_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_candidate_party_id"), ["party_id"], unique=False)

    op.create_table(
        "geo_vintage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("province_count", sa.Integer(), nullable=False),
        sa.Column("municipality_count", sa.Integer(), nullable=False),
        sa.Column("unit_count", sa.Integer(), nullable=False),
        sa.Column("population_total", sa.Integer(), nullable=False),
        sa.Column("processed_path", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("built_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_source.id"], name=op.f("fk_geo_vintage_source_id_data_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geo_vintage")),
        sa.UniqueConstraint("year", name=op.f("uq_geo_vintage_year")),
    )
    op.create_table(
        "legislature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=8), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("electoral_system", sa.String(length=32), nullable=False),
        sa.Column("size_rule", sa.String(length=48), nullable=False),
        sa.Column("term_years", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_legislature_province_id_province")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legislature")),
        sa.UniqueConstraint(
            "level", "jurisdiction_code", name=op.f("uq_legislature_level_jurisdiction_code")
        ),
    )
    op.create_table(
        "office",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("office_type", sa.String(length=24), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("district_code", sa.String(length=8), nullable=True),
        sa.Column("municipality_code", sa.String(length=6), nullable=True),
        sa.Column("senate_class", sa.Integer(), nullable=True),
        sa.Column("term_years", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_office_province_id_province")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_office")),
        sa.UniqueConstraint("code", name=op.f("uq_office_code")),
    )
    with op.batch_alter_table("office", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_office_office_type"), ["office_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_office_province_id"), ["province_id"], unique=False)

    op.create_table(
        "party_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=24), nullable=False),
        sa.Column("related_party_id", sa.Integer(), nullable=True),
        sa.Column("old_value", sa.String(length=160), nullable=True),
        sa.Column("new_value", sa.String(length=160), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], name=op.f("fk_party_event_party_id_party")),
        sa.ForeignKeyConstraint(
            ["related_party_id"], ["party.id"], name=op.f("fk_party_event_related_party_id_party")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_party_event")),
    )
    with op.batch_alter_table("party_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_party_event_party_id"), ["party_id"], unique=False)

    op.create_table(
        "party_modifier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], name=op.f("fk_party_modifier_party_id_party")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_party_modifier")),
        sa.UniqueConstraint(
            "party_id", "scope", "key", "source", name=op.f("uq_party_modifier_party_id_scope_key_source")
        ),
    )
    with op.batch_alter_table("party_modifier", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_party_modifier_party_id"), ["party_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_party_modifier_scope"), ["scope"], unique=False)

    op.create_table(
        "pollster_house_effect",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pollster_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("effect_pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"], ["party.id"], name=op.f("fk_pollster_house_effect_party_id_party")
        ),
        sa.ForeignKeyConstraint(
            ["pollster_id"], ["pollster.id"], name=op.f("fk_pollster_house_effect_pollster_id_pollster")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pollster_house_effect")),
        sa.UniqueConstraint(
            "pollster_id", "party_id", name=op.f("uq_pollster_house_effect_pollster_id_party_id")
        ),
    )
    with op.batch_alter_table("pollster_house_effect", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pollster_house_effect_pollster_id"), ["pollster_id"], unique=False
        )

    op.create_table(
        "apportionment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vintage_id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("population_basis", sa.String(length=32), nullable=False),
        sa.Column("total_seats", sa.Integer(), nullable=False),
        sa.Column("min_seats_per_province", sa.Integer(), nullable=False),
        sa.Column("senators_per_province", sa.Integer(), nullable=False),
        sa.Column("total_electoral_votes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["vintage_id"], ["geo_vintage.id"], name=op.f("fk_apportionment_vintage_id_geo_vintage")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apportionment")),
    )
    with op.batch_alter_table("apportionment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_apportionment_vintage_id"), ["vintage_id"], unique=False)

    op.create_table(
        "candidate_affiliation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("from_year", sa.Integer(), nullable=False),
        sa.Column("to_year", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidate.id"], name=op.f("fk_candidate_affiliation_candidate_id_candidate")
        ),
        sa.ForeignKeyConstraint(
            ["party_id"], ["party.id"], name=op.f("fk_candidate_affiliation_party_id_party")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_affiliation")),
    )
    with op.batch_alter_table("candidate_affiliation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_affiliation_candidate_id"), ["candidate_id"], unique=False
        )

    op.create_table(
        "governor_seat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("office_id", sa.Integer(), nullable=False),
        sa.Column("lt_office_id", sa.Integer(), nullable=True),
        sa.Column("first_election_year", sa.Integer(), nullable=False),
        sa.Column("approval", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lt_office_id"], ["office.id"], name=op.f("fk_governor_seat_lt_office_id_office")
        ),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], name=op.f("fk_governor_seat_office_id_office")),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_governor_seat_province_id_province")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_governor_seat")),
        sa.UniqueConstraint("province_id", name=op.f("uq_governor_seat_province_id")),
    )
    op.create_table(
        "mayor_seat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("municipality_code", sa.String(length=6), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("office_id", sa.Integer(), nullable=False),
        sa.Column("first_election_year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], name=op.f("fk_mayor_seat_office_id_office")),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_mayor_seat_province_id_province")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mayor_seat")),
        sa.UniqueConstraint("municipality_code", name=op.f("uq_mayor_seat_municipality_code")),
    )
    op.create_table(
        "municipality",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vintage_id", sa.Integer(), nullable=False),
        sa.Column("cbs_code", sa.String(length=6), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("population_official", sa.Integer(), nullable=True),
        sa.Column("eligible_voters_est", sa.Integer(), nullable=False),
        sa.Column("area_km2", sa.Float(), nullable=False),
        sa.Column("land_area_km2", sa.Float(), nullable=False),
        sa.Column("density", sa.Float(), nullable=False),
        sa.Column("urbanity_class", sa.Integer(), nullable=True),
        sa.Column("address_density", sa.Float(), nullable=True),
        sa.Column("unit_count", sa.Integer(), nullable=False),
        sa.Column("centroid_lon", sa.Float(), nullable=False),
        sa.Column("centroid_lat", sa.Float(), nullable=False),
        sa.Column("centroid_x", sa.Float(), nullable=False),
        sa.Column("centroid_y", sa.Float(), nullable=False),
        sa.Column("geometry_wkb", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_municipality_province_id_province")
        ),
        sa.ForeignKeyConstraint(
            ["vintage_id"], ["geo_vintage.id"], name=op.f("fk_municipality_vintage_id_geo_vintage")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_municipality")),
        sa.UniqueConstraint("vintage_id", "cbs_code", name=op.f("uq_municipality_vintage_id_cbs_code")),
    )
    with op.batch_alter_table("municipality", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_municipality_cbs_code"), ["cbs_code"], unique=False)
        batch_op.create_index(batch_op.f("ix_municipality_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_municipality_province_id"), ["province_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_municipality_vintage_id"), ["vintage_id"], unique=False)

    op.create_table(
        "municipality_lineage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_vintage_id", sa.Integer(), nullable=False),
        sa.Column("to_vintage_id", sa.Integer(), nullable=False),
        sa.Column("from_code", sa.String(length=6), nullable=False),
        sa.Column("to_code", sa.String(length=6), nullable=False),
        sa.Column("population_weight", sa.Float(), nullable=False),
        sa.Column("event", sa.String(length=24), nullable=False),
        sa.Column("effective_date", sa.String(length=10), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_vintage_id"],
            ["geo_vintage.id"],
            name=op.f("fk_municipality_lineage_from_vintage_id_geo_vintage"),
        ),
        sa.ForeignKeyConstraint(
            ["to_vintage_id"],
            ["geo_vintage.id"],
            name=op.f("fk_municipality_lineage_to_vintage_id_geo_vintage"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_municipality_lineage")),
        sa.UniqueConstraint(
            "from_vintage_id",
            "to_vintage_id",
            "from_code",
            "to_code",
            name=op.f("uq_municipality_lineage_from_vintage_id_to_vintage_id_from_code_to_code"),
        ),
    )
    op.create_table(
        "province_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("vintage_id", sa.Integer(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("population_official", sa.Integer(), nullable=True),
        sa.Column("eligible_voters_est", sa.Integer(), nullable=False),
        sa.Column("area_km2", sa.Float(), nullable=False),
        sa.Column("land_area_km2", sa.Float(), nullable=False),
        sa.Column("density", sa.Float(), nullable=False),
        sa.Column("municipality_count", sa.Integer(), nullable=False),
        sa.Column("unit_count", sa.Integer(), nullable=False),
        sa.Column("centroid_lon", sa.Float(), nullable=False),
        sa.Column("centroid_lat", sa.Float(), nullable=False),
        sa.Column("geometry_wkb", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_province_stats_province_id_province")
        ),
        sa.ForeignKeyConstraint(
            ["vintage_id"], ["geo_vintage.id"], name=op.f("fk_province_stats_vintage_id_geo_vintage")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_province_stats")),
        sa.UniqueConstraint(
            "province_id", "vintage_id", name=op.f("uq_province_stats_province_id_vintage_id")
        ),
    )
    with op.batch_alter_table("province_stats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_province_stats_province_id"), ["province_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_province_stats_vintage_id"), ["vintage_id"], unique=False)

    op.create_table(
        "senate_seat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("seat_number", sa.Integer(), nullable=False),
        sa.Column("senate_class", sa.Integer(), nullable=False),
        sa.Column("office_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], name=op.f("fk_senate_seat_office_id_office")),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_senate_seat_province_id_province")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_senate_seat")),
        sa.UniqueConstraint("code", name=op.f("uq_senate_seat_code")),
        sa.UniqueConstraint(
            "province_id", "seat_number", name=op.f("uq_senate_seat_province_id_seat_number")
        ),
    )
    with op.batch_alter_table("senate_seat", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_senate_seat_province_id"), ["province_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_senate_seat_senate_class"), ["senate_class"], unique=False)

    op.create_table(
        "apportionment_seat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("apportionment_id", sa.Integer(), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("quota", sa.Float(), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("electoral_votes", sa.Integer(), nullable=False),
        sa.Column("persons_per_seat", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["apportionment_id"],
            ["apportionment.id"],
            name=op.f("fk_apportionment_seat_apportionment_id_apportionment"),
        ),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_apportionment_seat_province_id_province")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apportionment_seat")),
        sa.UniqueConstraint(
            "apportionment_id", "province_id", name=op.f("uq_apportionment_seat_apportionment_id_province_id")
        ),
    )
    with op.batch_alter_table("apportionment_seat", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_apportionment_seat_apportionment_id"), ["apportionment_id"], unique=False
        )

    op.create_table(
        "district_plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("chamber", sa.String(length=32), nullable=False),
        sa.Column("vintage_id", sa.Integer(), nullable=False),
        sa.Column("apportionment_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=48), nullable=False),
        sa.Column("config_json", sa.Text(), nullable=True),
        sa.Column("config_hash", sa.String(length=16), nullable=False),
        sa.Column("total_districts", sa.Integer(), nullable=False),
        sa.Column("max_abs_deviation_pct", sa.Float(), nullable=False),
        sa.Column("mean_abs_deviation_pct", sa.Float(), nullable=False),
        sa.Column("split_municipalities", sa.Integer(), nullable=False),
        sa.Column("noncontiguous_districts", sa.Integer(), nullable=False),
        sa.Column("overrides_applied", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("generation_seconds", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["apportionment_id"],
            ["apportionment.id"],
            name=op.f("fk_district_plan_apportionment_id_apportionment"),
        ),
        sa.ForeignKeyConstraint(
            ["vintage_id"], ["geo_vintage.id"], name=op.f("fk_district_plan_vintage_id_geo_vintage")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_district_plan")),
    )
    with op.batch_alter_table("district_plan", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_district_plan_vintage_id"), ["vintage_id"], unique=False)

    op.create_table(
        "geo_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vintage_id", sa.Integer(), nullable=False),
        sa.Column("cbs_code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("unit_kind", sa.String(length=16), nullable=False),
        sa.Column("wijk_code", sa.String(length=8), nullable=True),
        sa.Column("municipality_id", sa.Integer(), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("eligible_voters_est", sa.Integer(), nullable=False),
        sa.Column("area_km2", sa.Float(), nullable=False),
        sa.Column("land_area_km2", sa.Float(), nullable=False),
        sa.Column("density", sa.Float(), nullable=False),
        sa.Column("urbanity_class", sa.Integer(), nullable=True),
        sa.Column("address_density", sa.Float(), nullable=True),
        sa.Column("centroid_lon", sa.Float(), nullable=False),
        sa.Column("centroid_lat", sa.Float(), nullable=False),
        sa.Column("centroid_x", sa.Float(), nullable=False),
        sa.Column("centroid_y", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["municipality_id"], ["municipality.id"], name=op.f("fk_geo_unit_municipality_id_municipality")
        ),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_geo_unit_province_id_province")
        ),
        sa.ForeignKeyConstraint(
            ["vintage_id"], ["geo_vintage.id"], name=op.f("fk_geo_unit_vintage_id_geo_vintage")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geo_unit")),
        sa.UniqueConstraint("vintage_id", "cbs_code", name=op.f("uq_geo_unit_vintage_id_cbs_code")),
    )
    with op.batch_alter_table("geo_unit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_geo_unit_cbs_code"), ["cbs_code"], unique=False)
        batch_op.create_index(batch_op.f("ix_geo_unit_municipality_id"), ["municipality_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_geo_unit_province_id"), ["province_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_geo_unit_vintage_id"), ["vintage_id"], unique=False)

    op.create_table(
        "municipality_demographics",
        sa.Column("municipality_id", sa.Integer(), nullable=False),
        sa.Column("pct_age_0_15", sa.Float(), nullable=True),
        sa.Column("pct_age_15_25", sa.Float(), nullable=True),
        sa.Column("pct_age_25_45", sa.Float(), nullable=True),
        sa.Column("pct_age_45_65", sa.Float(), nullable=True),
        sa.Column("pct_age_65_plus", sa.Float(), nullable=True),
        sa.Column("pct_single_households", sa.Float(), nullable=True),
        sa.Column("pct_households_with_children", sa.Float(), nullable=True),
        sa.Column("avg_household_size", sa.Float(), nullable=True),
        sa.Column("pct_origin_nl", sa.Float(), nullable=True),
        sa.Column("pct_origin_europe", sa.Float(), nullable=True),
        sa.Column("pct_origin_non_europe", sa.Float(), nullable=True),
        sa.Column("pct_education_low", sa.Float(), nullable=True),
        sa.Column("pct_education_mid", sa.Float(), nullable=True),
        sa.Column("pct_education_high", sa.Float(), nullable=True),
        sa.Column("income_per_capita_keur", sa.Float(), nullable=True),
        sa.Column("pct_owner_occupied", sa.Float(), nullable=True),
        sa.Column("source_year_core", sa.Integer(), nullable=True),
        sa.Column("source_year_supplement", sa.Integer(), nullable=True),
        sa.Column("imputed_fields", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["municipality_id"],
            ["municipality.id"],
            name=op.f("fk_municipality_demographics_municipality_id_municipality"),
        ),
        sa.PrimaryKeyConstraint("municipality_id", name=op.f("pk_municipality_demographics")),
    )
    op.create_table(
        "election",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("election_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("election_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("vintage_id", sa.Integer(), nullable=False),
        sa.Column("apportionment_id", sa.Integer(), nullable=True),
        sa.Column("district_plan_id", sa.Integer(), nullable=True),
        sa.Column("previous_election_id", sa.Integer(), nullable=True),
        sa.Column("polls_close_local", sa.String(length=5), nullable=False),
        sa.Column("timezone", sa.String(length=40), nullable=False),
        sa.Column("national_environment_json", sa.Text(), nullable=True),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("simulated_at", sa.DateTime(), nullable=True),
        sa.Column("finalized_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["apportionment_id"],
            ["apportionment.id"],
            name=op.f("fk_election_apportionment_id_apportionment"),
        ),
        sa.ForeignKeyConstraint(
            ["district_plan_id"],
            ["district_plan.id"],
            name=op.f("fk_election_district_plan_id_district_plan"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_election_id"], ["election.id"], name=op.f("fk_election_previous_election_id_election")
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"], ["scenario.id"], name=op.f("fk_election_scenario_id_scenario")
        ),
        sa.ForeignKeyConstraint(
            ["vintage_id"], ["geo_vintage.id"], name=op.f("fk_election_vintage_id_geo_vintage")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_election")),
    )
    with op.batch_alter_table("election", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_election_year"), ["year"], unique=False)

    op.create_table(
        "geo_unit_demographics",
        sa.Column("geo_unit_id", sa.Integer(), nullable=False),
        sa.Column("pct_age_0_15", sa.Float(), nullable=True),
        sa.Column("pct_age_15_25", sa.Float(), nullable=True),
        sa.Column("pct_age_25_45", sa.Float(), nullable=True),
        sa.Column("pct_age_45_65", sa.Float(), nullable=True),
        sa.Column("pct_age_65_plus", sa.Float(), nullable=True),
        sa.Column("pct_single_households", sa.Float(), nullable=True),
        sa.Column("pct_households_with_children", sa.Float(), nullable=True),
        sa.Column("avg_household_size", sa.Float(), nullable=True),
        sa.Column("pct_origin_nl", sa.Float(), nullable=True),
        sa.Column("pct_origin_europe", sa.Float(), nullable=True),
        sa.Column("pct_origin_non_europe", sa.Float(), nullable=True),
        sa.Column("pct_education_low", sa.Float(), nullable=True),
        sa.Column("pct_education_mid", sa.Float(), nullable=True),
        sa.Column("pct_education_high", sa.Float(), nullable=True),
        sa.Column("income_per_capita_keur", sa.Float(), nullable=True),
        sa.Column("pct_owner_occupied", sa.Float(), nullable=True),
        sa.Column("source_year_core", sa.Integer(), nullable=True),
        sa.Column("source_year_supplement", sa.Integer(), nullable=True),
        sa.Column("imputed_fields", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["geo_unit_id"], ["geo_unit.id"], name=op.f("fk_geo_unit_demographics_geo_unit_id_geo_unit")
        ),
        sa.PrimaryKeyConstraint("geo_unit_id", name=op.f("pk_geo_unit_demographics")),
    )
    op.create_table(
        "house_district",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=True),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("eligible_voters_est", sa.Integer(), nullable=False),
        sa.Column("target_population", sa.Float(), nullable=False),
        sa.Column("deviation_pct", sa.Float(), nullable=False),
        sa.Column("area_km2", sa.Float(), nullable=False),
        sa.Column("polsby_popper", sa.Float(), nullable=True),
        sa.Column("reock", sa.Float(), nullable=True),
        sa.Column("convex_hull_ratio", sa.Float(), nullable=True),
        sa.Column("n_units", sa.Integer(), nullable=False),
        sa.Column("n_municipalities", sa.Integer(), nullable=False),
        sa.Column("n_split_municipalities", sa.Integer(), nullable=False),
        sa.Column("urban_share", sa.Float(), nullable=True),
        sa.Column("rural_share", sa.Float(), nullable=True),
        sa.Column("is_contiguous", sa.Boolean(), nullable=False),
        sa.Column("n_components", sa.Integer(), nullable=False),
        sa.Column("centroid_lon", sa.Float(), nullable=False),
        sa.Column("centroid_lat", sa.Float(), nullable=False),
        sa.Column("geometry_wkb", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["district_plan.id"], name=op.f("fk_house_district_plan_id_district_plan")
        ),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_house_district_province_id_province")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_house_district")),
        sa.UniqueConstraint("plan_id", "code", name=op.f("uq_house_district_plan_id_code")),
    )
    with op.batch_alter_table("house_district", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_house_district_code"), ["code"], unique=False)
        batch_op.create_index(batch_op.f("ix_house_district_plan_id"), ["plan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_house_district_province_id"), ["province_id"], unique=False)

    op.create_table(
        "district_adjacency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("district_a_id", sa.Integer(), nullable=False),
        sa.Column("district_b_id", sa.Integer(), nullable=False),
        sa.Column("shared_border_km", sa.Float(), nullable=False),
        sa.Column("via_water_link", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["district_a_id"],
            ["house_district.id"],
            name=op.f("fk_district_adjacency_district_a_id_house_district"),
        ),
        sa.ForeignKeyConstraint(
            ["district_b_id"],
            ["house_district.id"],
            name=op.f("fk_district_adjacency_district_b_id_house_district"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["district_plan.id"], name=op.f("fk_district_adjacency_plan_id_district_plan")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_district_adjacency")),
        sa.UniqueConstraint(
            "district_a_id", "district_b_id", name=op.f("uq_district_adjacency_district_a_id_district_b_id")
        ),
    )
    with op.batch_alter_table("district_adjacency", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_district_adjacency_plan_id"), ["plan_id"], unique=False)

    op.create_table(
        "district_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("geo_unit_id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["house_district.id"],
            name=op.f("fk_district_assignment_district_id_house_district"),
        ),
        sa.ForeignKeyConstraint(
            ["geo_unit_id"], ["geo_unit.id"], name=op.f("fk_district_assignment_geo_unit_id_geo_unit")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["district_plan.id"], name=op.f("fk_district_assignment_plan_id_district_plan")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_district_assignment")),
        sa.UniqueConstraint(
            "plan_id", "geo_unit_id", name=op.f("uq_district_assignment_plan_id_geo_unit_id")
        ),
    )
    with op.batch_alter_table("district_assignment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_district_assignment_district_id"), ["district_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_district_assignment_geo_unit_id"), ["geo_unit_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_district_assignment_plan_id"), ["plan_id"], unique=False)

    op.create_table(
        "district_municipality",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("municipality_id", sa.Integer(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("n_units", sa.Integer(), nullable=False),
        sa.Column("share_of_municipality", sa.Float(), nullable=False),
        sa.Column("share_of_district", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["house_district.id"],
            name=op.f("fk_district_municipality_district_id_house_district"),
        ),
        sa.ForeignKeyConstraint(
            ["municipality_id"],
            ["municipality.id"],
            name=op.f("fk_district_municipality_municipality_id_municipality"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_district_municipality")),
        sa.UniqueConstraint(
            "district_id",
            "municipality_id",
            name=op.f("uq_district_municipality_district_id_municipality_id"),
        ),
    )
    with op.batch_alter_table("district_municipality", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_district_municipality_district_id"), ["district_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_district_municipality_municipality_id"), ["municipality_id"], unique=False
        )

    op.create_table(
        "night_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_seq", sa.Integer(), nullable=False),
        sa.Column("sim_time_s", sa.Float(), nullable=False),
        sa.Column("speed", sa.Float(), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("total_events", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["election_id"], ["election.id"], name=op.f("fk_night_session_election_id_election")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_night_session")),
        sa.UniqueConstraint("election_id", name=op.f("uq_night_session_election_id")),
    )
    op.create_table(
        "race",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=False),
        sa.Column("race_type", sa.String(length=24), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("parent_race_id", sa.Integer(), nullable=True),
        sa.Column("office_id", sa.Integer(), nullable=True),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("municipality_id", sa.Integer(), nullable=True),
        sa.Column("senate_seat_id", sa.Integer(), nullable=True),
        sa.Column("electoral_votes", sa.Integer(), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("electoral_system", sa.String(length=32), nullable=False),
        sa.Column("is_special", sa.Boolean(), nullable=False),
        sa.Column("is_open_seat", sa.Boolean(), nullable=False),
        sa.Column("incumbent_candidate_id", sa.Integer(), nullable=True),
        sa.Column("incumbent_party_id", sa.Integer(), nullable=True),
        sa.Column("previous_race_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("winner_ballot_candidate_id", sa.Integer(), nullable=True),
        sa.Column("winner_party_id", sa.Integer(), nullable=True),
        sa.Column("total_votes", sa.Integer(), nullable=True),
        sa.Column("margin_votes", sa.Integer(), nullable=True),
        sa.Column("margin_pct", sa.Float(), nullable=True),
        sa.Column("turnout_pct", sa.Float(), nullable=True),
        sa.Column("flipped", sa.Boolean(), nullable=True),
        sa.Column("decided_by", sa.String(length=24), nullable=True),
        sa.Column("called_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["district_id"], ["house_district.id"], name=op.f("fk_race_district_id_house_district")
        ),
        sa.ForeignKeyConstraint(["election_id"], ["election.id"], name=op.f("fk_race_election_id_election")),
        sa.ForeignKeyConstraint(
            ["incumbent_candidate_id"],
            ["candidate.id"],
            name=op.f("fk_race_incumbent_candidate_id_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["incumbent_party_id"], ["party.id"], name=op.f("fk_race_incumbent_party_id_party")
        ),
        sa.ForeignKeyConstraint(
            ["municipality_id"], ["municipality.id"], name=op.f("fk_race_municipality_id_municipality")
        ),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], name=op.f("fk_race_office_id_office")),
        sa.ForeignKeyConstraint(["parent_race_id"], ["race.id"], name=op.f("fk_race_parent_race_id_race")),
        sa.ForeignKeyConstraint(
            ["previous_race_id"], ["race.id"], name=op.f("fk_race_previous_race_id_race")
        ),
        sa.ForeignKeyConstraint(["province_id"], ["province.id"], name=op.f("fk_race_province_id_province")),
        sa.ForeignKeyConstraint(
            ["senate_seat_id"], ["senate_seat.id"], name=op.f("fk_race_senate_seat_id_senate_seat")
        ),
        *(
            [
                sa.ForeignKeyConstraint(
                    ["winner_ballot_candidate_id"], ["ballot_candidate.id"], name=_RACE_WINNER_FK
                )
            ]
            if sqlite
            else []
        ),
        sa.ForeignKeyConstraint(
            ["winner_party_id"], ["party.id"], name=op.f("fk_race_winner_party_id_party")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race")),
        sa.UniqueConstraint("election_id", "code", name=op.f("uq_race_election_id_code")),
    )
    with op.batch_alter_table("race", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_race_district_id"), ["district_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_race_election_id"), ["election_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_race_municipality_id"), ["municipality_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_race_parent_race_id"), ["parent_race_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_race_province_id"), ["province_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_race_race_type"), ["race_type"], unique=False)

    op.create_table(
        "reporting_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("sim_time_s", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("municipality_id", sa.Integer(), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("ballots_in_batch", sa.Integer(), nullable=False),
        sa.Column("municipality_fraction_after", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["election_id"], ["election.id"], name=op.f("fk_reporting_event_election_id_election")
        ),
        sa.ForeignKeyConstraint(
            ["municipality_id"],
            ["municipality.id"],
            name=op.f("fk_reporting_event_municipality_id_municipality"),
        ),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_reporting_event_province_id_province")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reporting_event")),
        sa.UniqueConstraint("election_id", "seq", name=op.f("uq_reporting_event_election_id_seq")),
    )
    with op.batch_alter_table("reporting_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reporting_event_election_id"), ["election_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reporting_event_municipality_id"), ["municipality_id"], unique=False
        )

    op.create_table(
        "simulation_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=True),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("n_simulations", sa.Integer(), nullable=True),
        sa.Column("config_hash", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("summary_json", sa.Text(), nullable=True),
        sa.Column("code_version", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["election_id"], ["election.id"], name=op.f("fk_simulation_run_election_id_election")
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"], ["scenario.id"], name=op.f("fk_simulation_run_scenario_id_scenario")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_run")),
    )
    with op.batch_alter_table("simulation_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_simulation_run_election_id"), ["election_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_simulation_run_kind"), ["kind"], unique=False)

    op.create_table(
        "ballot_candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=True),
        sa.Column("running_mate_id", sa.Integer(), nullable=True),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("ballot_order", sa.Integer(), nullable=False),
        sa.Column("ballot_name", sa.String(length=200), nullable=False),
        sa.Column("line_key", sa.String(length=80), nullable=True),
        sa.Column("quality_snapshot", sa.Float(), nullable=True),
        sa.Column("party_code_snapshot", sa.String(length=12), nullable=True),
        sa.Column("party_name_snapshot", sa.String(length=120), nullable=True),
        sa.Column("party_abbr_snapshot", sa.String(length=16), nullable=True),
        sa.Column("party_color_snapshot", sa.String(length=9), nullable=True),
        sa.Column("is_incumbent", sa.Boolean(), nullable=False),
        sa.Column("is_write_in", sa.Boolean(), nullable=False),
        sa.Column("withdrawn", sa.Boolean(), nullable=False),
        sa.Column("withdrawn_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidate.id"], name=op.f("fk_ballot_candidate_candidate_id_candidate")
        ),
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], name=op.f("fk_ballot_candidate_party_id_party")),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], name=op.f("fk_ballot_candidate_race_id_race")),
        sa.ForeignKeyConstraint(
            ["running_mate_id"], ["candidate.id"], name=op.f("fk_ballot_candidate_running_mate_id_candidate")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ballot_candidate")),
        sa.UniqueConstraint("race_id", "ballot_order", name=op.f("uq_ballot_candidate_race_id_ballot_order")),
    )
    with op.batch_alter_table("ballot_candidate", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ballot_candidate_candidate_id"), ["candidate_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ballot_candidate_party_id"), ["party_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ballot_candidate_race_id"), ["race_id"], unique=False)

    if not sqlite:
        op.create_foreign_key(
            _RACE_WINNER_FK, "race", "ballot_candidate", ["winner_ballot_candidate_id"], ["id"]
        )
    op.create_table(
        "forecast_aggregate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=24), nullable=False),
        sa.Column("key", sa.String(length=24), nullable=False),
        sa.Column("mean", sa.Float(), nullable=False),
        sa.Column("median", sa.Float(), nullable=False),
        sa.Column("p05", sa.Float(), nullable=False),
        sa.Column("p25", sa.Float(), nullable=False),
        sa.Column("p75", sa.Float(), nullable=False),
        sa.Column("p95", sa.Float(), nullable=False),
        sa.Column("prob_majority", sa.Float(), nullable=True),
        sa.Column("prob_plurality", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["simulation_run.id"], name=op.f("fk_forecast_aggregate_run_id_simulation_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_aggregate")),
        sa.UniqueConstraint(
            "run_id", "subject", "key", name=op.f("uq_forecast_aggregate_run_id_subject_key")
        ),
    )
    with op.batch_alter_table("forecast_aggregate", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forecast_aggregate_run_id"), ["run_id"], unique=False)

    op.create_table(
        "forecast_combination",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("combination_key", sa.Text(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=False),
        sa.Column("ev_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["simulation_run.id"], name=op.f("fk_forecast_combination_run_id_simulation_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_combination")),
    )
    with op.batch_alter_table("forecast_combination", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forecast_combination_run_id"), ["run_id"], unique=False)

    op.create_table(
        "forecast_distribution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=24), nullable=False),
        sa.Column("key", sa.String(length=24), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["simulation_run.id"], name=op.f("fk_forecast_distribution_run_id_simulation_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_distribution")),
    )
    with op.batch_alter_table("forecast_distribution", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forecast_distribution_run_id"), ["run_id"], unique=False)

    op.create_table(
        "legislature_seat_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("legislature_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("votes", sa.Integer(), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["legislature_id"],
            ["legislature.id"],
            name=op.f("fk_legislature_seat_result_legislature_id_legislature"),
        ),
        sa.ForeignKeyConstraint(
            ["party_id"], ["party.id"], name=op.f("fk_legislature_seat_result_party_id_party")
        ),
        sa.ForeignKeyConstraint(
            ["race_id"], ["race.id"], name=op.f("fk_legislature_seat_result_race_id_race")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legislature_seat_result")),
        sa.UniqueConstraint("race_id", "party_id", name=op.f("uq_legislature_seat_result_race_id_party_id")),
    )
    with op.batch_alter_table("legislature_seat_result", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_legislature_seat_result_race_id"), ["race_id"], unique=False)

    op.create_table(
        "office_holder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("office_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("term_start", sa.Date(), nullable=False),
        sa.Column("term_end", sa.Date(), nullable=True),
        sa.Column("ended_on", sa.Date(), nullable=True),
        sa.Column("start_reason", sa.String(length=24), nullable=False),
        sa.Column("end_reason", sa.String(length=24), nullable=True),
        sa.Column("election_race_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidate.id"], name=op.f("fk_office_holder_candidate_id_candidate")
        ),
        sa.ForeignKeyConstraint(
            ["election_race_id"], ["race.id"], name=op.f("fk_office_holder_election_race_id_race")
        ),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], name=op.f("fk_office_holder_office_id_office")),
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], name=op.f("fk_office_holder_party_id_party")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_office_holder")),
    )
    with op.batch_alter_table("office_holder", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_office_holder_candidate_id"), ["candidate_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_office_holder_office_id"), ["office_id"], unique=False)

    op.create_table(
        "poll",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=True),
        sa.Column("race_id", sa.Integer(), nullable=True),
        sa.Column("pollster_id", sa.Integer(), nullable=False),
        sa.Column("poll_type", sa.String(length=24), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("district_code", sa.String(length=8), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("population", sa.String(length=4), nullable=False),
        sa.Column("method", sa.String(length=24), nullable=False),
        sa.Column("margin_of_error", sa.Float(), nullable=True),
        sa.Column("undecided_pct", sa.Float(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("quality_rating", sa.Float(), nullable=True),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["election_id"], ["election.id"], name=op.f("fk_poll_election_id_election")),
        sa.ForeignKeyConstraint(["pollster_id"], ["pollster.id"], name=op.f("fk_poll_pollster_id_pollster")),
        sa.ForeignKeyConstraint(["province_id"], ["province.id"], name=op.f("fk_poll_province_id_province")),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], name=op.f("fk_poll_race_id_race")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_poll")),
    )
    with op.batch_alter_table("poll", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_poll_election_id"), ["election_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_poll_end_date"), ["end_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_poll_poll_type"), ["poll_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_poll_pollster_id"), ["pollster_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_poll_race_id"), ["race_id"], unique=False)

    op.create_table(
        "recount",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("threshold_pct", sa.Float(), nullable=True),
        sa.Column("margin_before_votes", sa.Integer(), nullable=False),
        sa.Column("margin_before_pct", sa.Float(), nullable=False),
        sa.Column("margin_after_votes", sa.Integer(), nullable=True),
        sa.Column("margin_after_pct", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("outcome_changed", sa.Boolean(), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], name=op.f("fk_recount_race_id_race")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recount")),
    )
    with op.batch_alter_table("recount", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recount_race_id"), ["race_id"], unique=False)

    op.create_table(
        "reporting_event_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("geo_unit_id", sa.Integer(), nullable=False),
        sa.Column("fraction", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["reporting_event.id"],
            name=op.f("fk_reporting_event_unit_event_id_reporting_event"),
        ),
        sa.ForeignKeyConstraint(
            ["geo_unit_id"], ["geo_unit.id"], name=op.f("fk_reporting_event_unit_geo_unit_id_geo_unit")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reporting_event_unit")),
        sa.UniqueConstraint(
            "event_id", "geo_unit_id", name=op.f("uq_reporting_event_unit_event_id_geo_unit_id")
        ),
    )
    with op.batch_alter_table("reporting_event_unit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reporting_event_unit_event_id"), ["event_id"], unique=False)

    op.create_table(
        "turnout_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=12), nullable=False),
        sa.Column("geo_key", sa.String(length=16), nullable=False),
        sa.Column("geo_unit_id", sa.Integer(), nullable=True),
        sa.Column("municipality_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("eligible_voters", sa.Integer(), nullable=False),
        sa.Column("ballots_cast", sa.Integer(), nullable=False),
        sa.Column("valid_votes", sa.Integer(), nullable=False),
        sa.Column("blank_votes", sa.Integer(), nullable=False),
        sa.Column("invalid_votes", sa.Integer(), nullable=False),
        sa.Column("turnout_pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["district_id"], ["house_district.id"], name=op.f("fk_turnout_result_district_id_house_district")
        ),
        sa.ForeignKeyConstraint(
            ["election_id"], ["election.id"], name=op.f("fk_turnout_result_election_id_election")
        ),
        sa.ForeignKeyConstraint(
            ["geo_unit_id"], ["geo_unit.id"], name=op.f("fk_turnout_result_geo_unit_id_geo_unit")
        ),
        sa.ForeignKeyConstraint(
            ["municipality_id"],
            ["municipality.id"],
            name=op.f("fk_turnout_result_municipality_id_municipality"),
        ),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_turnout_result_province_id_province")
        ),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], name=op.f("fk_turnout_result_race_id_race")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turnout_result")),
        sa.UniqueConstraint("race_id", "geo_key", name=op.f("uq_turnout_result_race_id_geo_key")),
    )
    with op.batch_alter_table("turnout_result", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_turnout_result_election_id"), ["election_id"], unique=False)
        batch_op.create_index("ix_turnout_result_race_level", ["race_id", "level"], unique=False)

    op.create_table(
        "campaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=True),
        sa.Column("ballot_candidate_id", sa.Integer(), nullable=True),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("budget", sa.Float(), nullable=False),
        sa.Column("strategy", sa.String(length=24), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ballot_candidate_id"],
            ["ballot_candidate.id"],
            name=op.f("fk_campaign_ballot_candidate_id_ballot_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["election_id"], ["election.id"], name=op.f("fk_campaign_election_id_election")
        ),
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], name=op.f("fk_campaign_party_id_party")),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], name=op.f("fk_campaign_race_id_race")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign")),
        sa.UniqueConstraint(
            "race_id", "ballot_candidate_id", name=op.f("uq_campaign_race_id_ballot_candidate_id")
        ),
    )
    with op.batch_alter_table("campaign", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_campaign_election_id"), ["election_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaign_race_id"), ["race_id"], unique=False)

    op.create_table(
        "contingent_election",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("finalists_json", sa.Text(), nullable=False),
        sa.Column("ballots_json", sa.Text(), nullable=False),
        sa.Column("winner_ballot_candidate_id", sa.Integer(), nullable=True),
        sa.Column("vp_winner_candidate_id", sa.Integer(), nullable=True),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], name=op.f("fk_contingent_election_race_id_race")),
        sa.ForeignKeyConstraint(
            ["vp_winner_candidate_id"],
            ["candidate.id"],
            name=op.f("fk_contingent_election_vp_winner_candidate_id_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_ballot_candidate_id"],
            ["ballot_candidate.id"],
            name=op.f("fk_contingent_election_winner_ballot_candidate_id_ballot_candidate"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contingent_election")),
        sa.UniqueConstraint("race_id", name=op.f("uq_contingent_election_race_id")),
    )
    op.create_table(
        "election_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("ballot_candidate_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=12), nullable=False),
        sa.Column("geo_key", sa.String(length=16), nullable=False),
        sa.Column("geo_unit_id", sa.Integer(), nullable=True),
        sa.Column("municipality_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("votes", sa.Integer(), nullable=False),
        sa.Column("share", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ballot_candidate_id"],
            ["ballot_candidate.id"],
            name=op.f("fk_election_result_ballot_candidate_id_ballot_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["district_id"], ["house_district.id"], name=op.f("fk_election_result_district_id_house_district")
        ),
        sa.ForeignKeyConstraint(
            ["geo_unit_id"], ["geo_unit.id"], name=op.f("fk_election_result_geo_unit_id_geo_unit")
        ),
        sa.ForeignKeyConstraint(
            ["municipality_id"],
            ["municipality.id"],
            name=op.f("fk_election_result_municipality_id_municipality"),
        ),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_election_result_province_id_province")
        ),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], name=op.f("fk_election_result_race_id_race")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_election_result")),
        sa.UniqueConstraint(
            "race_id",
            "ballot_candidate_id",
            "geo_key",
            name=op.f("uq_election_result_race_id_ballot_candidate_id_geo_key"),
        ),
    )
    with op.batch_alter_table("election_result", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_election_result_ballot_candidate_id"), ["ballot_candidate_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_election_result_geo_unit_id"), ["geo_unit_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_election_result_municipality_id"), ["municipality_id"], unique=False
        )
        batch_op.create_index("ix_election_result_race_level", ["race_id", "level"], unique=False)

    op.create_table(
        "electoral_vote_allocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("province_race_id", sa.Integer(), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("ballot_candidate_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=True),
        sa.Column("electoral_votes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ballot_candidate_id"],
            ["ballot_candidate.id"],
            name=op.f("fk_electoral_vote_allocation_ballot_candidate_id_ballot_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate.id"],
            name=op.f("fk_electoral_vote_allocation_candidate_id_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["province_id"], ["province.id"], name=op.f("fk_electoral_vote_allocation_province_id_province")
        ),
        sa.ForeignKeyConstraint(
            ["province_race_id"], ["race.id"], name=op.f("fk_electoral_vote_allocation_province_race_id_race")
        ),
        sa.ForeignKeyConstraint(
            ["race_id"], ["race.id"], name=op.f("fk_electoral_vote_allocation_race_id_race")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_electoral_vote_allocation")),
        sa.UniqueConstraint(
            "race_id",
            "province_id",
            "ballot_candidate_id",
            name=op.f("uq_electoral_vote_allocation_race_id_province_id_ballot_candidate_id"),
        ),
    )
    with op.batch_alter_table("electoral_vote_allocation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_electoral_vote_allocation_race_id"), ["race_id"], unique=False)

    op.create_table(
        "forecast_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("ballot_candidate_id", sa.Integer(), nullable=False),
        sa.Column("win_probability", sa.Float(), nullable=False),
        sa.Column("mean_share", sa.Float(), nullable=False),
        sa.Column("p05_share", sa.Float(), nullable=False),
        sa.Column("p50_share", sa.Float(), nullable=False),
        sa.Column("p95_share", sa.Float(), nullable=False),
        sa.Column("mean_votes", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ballot_candidate_id"],
            ["ballot_candidate.id"],
            name=op.f("fk_forecast_summary_ballot_candidate_id_ballot_candidate"),
        ),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], name=op.f("fk_forecast_summary_race_id_race")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["simulation_run.id"], name=op.f("fk_forecast_summary_run_id_simulation_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_summary")),
        sa.UniqueConstraint(
            "run_id",
            "race_id",
            "ballot_candidate_id",
            name=op.f("uq_forecast_summary_run_id_race_id_ballot_candidate_id"),
        ),
    )
    with op.batch_alter_table("forecast_summary", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forecast_summary_race_id"), ["race_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_forecast_summary_run_id"), ["run_id"], unique=False)

    op.create_table(
        "poll_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("poll_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("candidate_id", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("value_pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidate.id"], name=op.f("fk_poll_result_candidate_id_candidate")
        ),
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], name=op.f("fk_poll_result_party_id_party")),
        sa.ForeignKeyConstraint(["poll_id"], ["poll.id"], name=op.f("fk_poll_result_poll_id_poll")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_poll_result")),
    )
    with op.batch_alter_table("poll_result", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_poll_result_poll_id"), ["poll_id"], unique=False)

    op.create_table(
        "race_call",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("ballot_candidate_id", sa.Integer(), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("sim_time_s", sa.Float(), nullable=False),
        sa.Column("called_at", sa.DateTime(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("reporting_pct", sa.Float(), nullable=False),
        sa.Column("leader_margin_pct", sa.Float(), nullable=True),
        sa.Column("win_probability", sa.Float(), nullable=True),
        sa.Column("evidence_json", sa.Text(), nullable=False),
        sa.Column("is_manual", sa.Boolean(), nullable=False),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ballot_candidate_id"],
            ["ballot_candidate.id"],
            name=op.f("fk_race_call_ballot_candidate_id_ballot_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["election_id"], ["election.id"], name=op.f("fk_race_call_election_id_election")
        ),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], name=op.f("fk_race_call_race_id_race")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race_call")),
    )
    with op.batch_alter_table("race_call", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_race_call_election_id"), ["election_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_race_call_race_id"), ["race_id"], unique=False)

    op.create_table(
        "recount_adjustment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recount_id", sa.Integer(), nullable=False),
        sa.Column("geo_unit_id", sa.Integer(), nullable=False),
        sa.Column("ballot_candidate_id", sa.Integer(), nullable=True),
        sa.Column("pile", sa.String(length=8), nullable=False),
        sa.Column("votes_before", sa.Integer(), nullable=False),
        sa.Column("votes_after", sa.Integer(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["ballot_candidate_id"],
            ["ballot_candidate.id"],
            name=op.f("fk_recount_adjustment_ballot_candidate_id_ballot_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["geo_unit_id"], ["geo_unit.id"], name=op.f("fk_recount_adjustment_geo_unit_id_geo_unit")
        ),
        sa.ForeignKeyConstraint(
            ["recount_id"], ["recount.id"], name=op.f("fk_recount_adjustment_recount_id_recount")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recount_adjustment")),
    )
    with op.batch_alter_table("recount_adjustment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recount_adjustment_recount_id"), ["recount_id"], unique=False)

    op.create_table(
        "vacancy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("office_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("appointed_holder_id", sa.Integer(), nullable=True),
        sa.Column("special_race_id", sa.Integer(), nullable=True),
        sa.Column("resolved_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointed_holder_id"],
            ["office_holder.id"],
            name=op.f("fk_vacancy_appointed_holder_id_office_holder"),
        ),
        sa.ForeignKeyConstraint(["office_id"], ["office.id"], name=op.f("fk_vacancy_office_id_office")),
        sa.ForeignKeyConstraint(
            ["special_race_id"], ["race.id"], name=op.f("fk_vacancy_special_race_id_race")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vacancy")),
    )
    with op.batch_alter_table("vacancy", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vacancy_office_id"), ["office_id"], unique=False)

    op.create_table(
        "campaign_allocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("target_level", sa.String(length=12), nullable=False),
        sa.Column("target_code", sa.String(length=12), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=True),
        sa.Column("proceeds", sa.Float(), nullable=True),
        sa.Column("week", sa.Integer(), nullable=True),
        sa.Column("expected_effect", sa.Float(), nullable=True),
        sa.Column("realized_effect", sa.Float(), nullable=True),
        sa.Column("turnout_effect", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaign.id"], name=op.f("fk_campaign_allocation_campaign_id_campaign")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_allocation")),
    )
    with op.batch_alter_table("campaign_allocation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_campaign_allocation_campaign_id"), ["campaign_id"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("campaign_allocation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_allocation_campaign_id"))

    op.drop_table("campaign_allocation")
    with op.batch_alter_table("vacancy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vacancy_office_id"))

    op.drop_table("vacancy")
    with op.batch_alter_table("recount_adjustment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recount_adjustment_recount_id"))

    op.drop_table("recount_adjustment")
    with op.batch_alter_table("race_call", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_race_call_race_id"))
        batch_op.drop_index(batch_op.f("ix_race_call_election_id"))

    op.drop_table("race_call")
    with op.batch_alter_table("poll_result", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_poll_result_poll_id"))

    op.drop_table("poll_result")
    with op.batch_alter_table("forecast_summary", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_summary_run_id"))
        batch_op.drop_index(batch_op.f("ix_forecast_summary_race_id"))

    op.drop_table("forecast_summary")
    with op.batch_alter_table("electoral_vote_allocation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_electoral_vote_allocation_race_id"))

    op.drop_table("electoral_vote_allocation")
    with op.batch_alter_table("election_result", schema=None) as batch_op:
        batch_op.drop_index("ix_election_result_race_level")
        batch_op.drop_index(batch_op.f("ix_election_result_municipality_id"))
        batch_op.drop_index(batch_op.f("ix_election_result_geo_unit_id"))
        batch_op.drop_index(batch_op.f("ix_election_result_ballot_candidate_id"))

    op.drop_table("election_result")
    op.drop_table("contingent_election")
    with op.batch_alter_table("campaign", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_race_id"))
        batch_op.drop_index(batch_op.f("ix_campaign_election_id"))

    op.drop_table("campaign")
    with op.batch_alter_table("turnout_result", schema=None) as batch_op:
        batch_op.drop_index("ix_turnout_result_race_level")
        batch_op.drop_index(batch_op.f("ix_turnout_result_election_id"))

    op.drop_table("turnout_result")
    with op.batch_alter_table("reporting_event_unit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reporting_event_unit_event_id"))

    op.drop_table("reporting_event_unit")
    with op.batch_alter_table("recount", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recount_race_id"))

    op.drop_table("recount")
    with op.batch_alter_table("poll", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_poll_race_id"))
        batch_op.drop_index(batch_op.f("ix_poll_pollster_id"))
        batch_op.drop_index(batch_op.f("ix_poll_poll_type"))
        batch_op.drop_index(batch_op.f("ix_poll_end_date"))
        batch_op.drop_index(batch_op.f("ix_poll_election_id"))

    op.drop_table("poll")
    with op.batch_alter_table("office_holder", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_office_holder_office_id"))
        batch_op.drop_index(batch_op.f("ix_office_holder_candidate_id"))

    op.drop_table("office_holder")
    with op.batch_alter_table("legislature_seat_result", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_legislature_seat_result_race_id"))

    op.drop_table("legislature_seat_result")
    with op.batch_alter_table("forecast_distribution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_distribution_run_id"))

    op.drop_table("forecast_distribution")
    with op.batch_alter_table("forecast_combination", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_combination_run_id"))

    op.drop_table("forecast_combination")
    with op.batch_alter_table("forecast_aggregate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_aggregate_run_id"))

    op.drop_table("forecast_aggregate")
    op.execute(sa.text("UPDATE race SET winner_ballot_candidate_id = NULL"))
    if not _is_sqlite():
        op.drop_constraint(_RACE_WINNER_FK, "race", type_="foreignkey")
    with op.batch_alter_table("ballot_candidate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ballot_candidate_race_id"))
        batch_op.drop_index(batch_op.f("ix_ballot_candidate_party_id"))
        batch_op.drop_index(batch_op.f("ix_ballot_candidate_candidate_id"))

    op.drop_table("ballot_candidate")
    with op.batch_alter_table("simulation_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_simulation_run_kind"))
        batch_op.drop_index(batch_op.f("ix_simulation_run_election_id"))

    op.drop_table("simulation_run")
    with op.batch_alter_table("reporting_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reporting_event_municipality_id"))
        batch_op.drop_index(batch_op.f("ix_reporting_event_election_id"))

    op.drop_table("reporting_event")
    with op.batch_alter_table("race", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_race_race_type"))
        batch_op.drop_index(batch_op.f("ix_race_province_id"))
        batch_op.drop_index(batch_op.f("ix_race_parent_race_id"))
        batch_op.drop_index(batch_op.f("ix_race_municipality_id"))
        batch_op.drop_index(batch_op.f("ix_race_election_id"))
        batch_op.drop_index(batch_op.f("ix_race_district_id"))

    op.drop_table("race")
    op.drop_table("night_session")
    with op.batch_alter_table("district_municipality", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_district_municipality_municipality_id"))
        batch_op.drop_index(batch_op.f("ix_district_municipality_district_id"))

    op.drop_table("district_municipality")
    with op.batch_alter_table("district_assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_district_assignment_plan_id"))
        batch_op.drop_index(batch_op.f("ix_district_assignment_geo_unit_id"))
        batch_op.drop_index(batch_op.f("ix_district_assignment_district_id"))

    op.drop_table("district_assignment")
    with op.batch_alter_table("district_adjacency", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_district_adjacency_plan_id"))

    op.drop_table("district_adjacency")
    with op.batch_alter_table("house_district", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_house_district_province_id"))
        batch_op.drop_index(batch_op.f("ix_house_district_plan_id"))
        batch_op.drop_index(batch_op.f("ix_house_district_code"))

    op.drop_table("house_district")
    op.drop_table("geo_unit_demographics")
    with op.batch_alter_table("election", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_election_year"))

    op.drop_table("election")
    op.drop_table("municipality_demographics")
    with op.batch_alter_table("geo_unit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_geo_unit_vintage_id"))
        batch_op.drop_index(batch_op.f("ix_geo_unit_province_id"))
        batch_op.drop_index(batch_op.f("ix_geo_unit_municipality_id"))
        batch_op.drop_index(batch_op.f("ix_geo_unit_cbs_code"))

    op.drop_table("geo_unit")
    with op.batch_alter_table("district_plan", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_district_plan_vintage_id"))

    op.drop_table("district_plan")
    with op.batch_alter_table("apportionment_seat", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apportionment_seat_apportionment_id"))

    op.drop_table("apportionment_seat")
    with op.batch_alter_table("senate_seat", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_senate_seat_senate_class"))
        batch_op.drop_index(batch_op.f("ix_senate_seat_province_id"))

    op.drop_table("senate_seat")
    with op.batch_alter_table("province_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_province_stats_vintage_id"))
        batch_op.drop_index(batch_op.f("ix_province_stats_province_id"))

    op.drop_table("province_stats")
    op.drop_table("municipality_lineage")
    with op.batch_alter_table("municipality", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_municipality_vintage_id"))
        batch_op.drop_index(batch_op.f("ix_municipality_province_id"))
        batch_op.drop_index(batch_op.f("ix_municipality_name"))
        batch_op.drop_index(batch_op.f("ix_municipality_cbs_code"))

    op.drop_table("municipality")
    op.drop_table("mayor_seat")
    op.drop_table("governor_seat")
    with op.batch_alter_table("candidate_affiliation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_affiliation_candidate_id"))

    op.drop_table("candidate_affiliation")
    with op.batch_alter_table("apportionment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apportionment_vintage_id"))

    op.drop_table("apportionment")
    with op.batch_alter_table("pollster_house_effect", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pollster_house_effect_pollster_id"))

    op.drop_table("pollster_house_effect")
    with op.batch_alter_table("party_modifier", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_party_modifier_scope"))
        batch_op.drop_index(batch_op.f("ix_party_modifier_party_id"))

    op.drop_table("party_modifier")
    with op.batch_alter_table("party_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_party_event_party_id"))

    op.drop_table("party_event")
    with op.batch_alter_table("office", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_office_province_id"))
        batch_op.drop_index(batch_op.f("ix_office_office_type"))

    op.drop_table("office")
    op.drop_table("legislature")
    op.drop_table("geo_vintage")
    with op.batch_alter_table("candidate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_party_id"))
        batch_op.drop_index(batch_op.f("ix_candidate_full_name"))

    op.drop_table("candidate")
    op.drop_table("scenario")
    op.drop_table("province")
    op.drop_table("pollster")
    op.drop_table("party")
    op.drop_table("data_source")
    op.drop_table("app_meta")
