"""Shared polling vocabulary: poll types, column schemas and race ↔ poll-group mapping.

Every poll in the application is FICTIONAL (invented pollsters) and every number in it is
SIMULATED.  This module is dependency-free (no SQLAlchemy) so engines and services can share it.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from typing import Protocol

from app.core.constitution import DataCategory

#: Poll types understood by generation, aggregation and persistence.
POLL_TYPES: tuple[str, ...] = (
    "national_president",
    "province_president",
    "house_district",
    "senate",
    "governor",
    "generic_house",
    "favorability",
)

#: Poll types whose geography is the whole country (``geo_code == NATIONAL_GEO``).
NATIONAL_POLL_TYPES: frozenset[str] = frozenset({"national_president", "generic_house", "favorability"})

#: ``geo_code`` of national polls.
NATIONAL_GEO: str = "NL"

#: Screened populations: likely voters, registered voters, all adults.
POPULATIONS: tuple[str, ...] = ("LV", "RV", "A")

#: Columns of the polls frame consumed by :func:`app.polling.aggregate.aggregate_polls`.
POLL_COLUMNS: tuple[str, ...] = (
    "poll_id",
    "pollster",
    "poll_type",
    "geo_code",
    "start_date",
    "end_date",
    "sample_size",
    "population",
    "method",
    "undecided_pct",
    "quality_rating",
)

#: Columns of the poll-results frame (one row per poll × option).
RESULT_COLUMNS: tuple[str, ...] = ("poll_id", "key", "value_pct")

#: Mapping from poll type to the count field of :class:`app.scenarios.schema.PollingSpec`.
SPEC_COUNT_FIELDS: dict[str, str] = {
    "national_president": "national_polls",
    "province_president": "province_polls",
    "house_district": "district_polls",
    "senate": "senate_polls",
    "governor": "governor_polls",
    "generic_house": "generic_ballot_polls",
}

#: Label attached to every generated / stored poll.
FICTIONAL_POLL_SOURCE: str = (
    "FICTIONAL poll by an invented pollster, generated by the NL Federal Election Simulator (SIMULATED data)"
)

POLL_DATA_CATEGORY: str = DataCategory.SIMULATED.value

_PROVINCE_RE = re.compile(r"^[A-Z]{2}$")
_PROVINCE_PREFIX_RE = re.compile(r"^([A-Z]{2})-")


class PollsterLike(Protocol):
    """Structural type of a pollster description.

    Satisfied by :class:`app.polling.config.PollsterConfig` and by the scenario's
    :class:`app.scenarios.schema.PollsterSpec`.  Optional attributes read with ``getattr``:
    ``rating_label``, ``activity``, ``poll_types``, ``population``, ``undecided_offset_pp``.
    """

    name: str
    rating: float
    method: str
    typical_sample: int
    house_effects: Mapping[str, float]


def race_code_for(poll_type: str, geo_code: str) -> str | None:
    """Canonical race code of a poll group, or ``None`` when the poll is not about one race.

    ``senate`` polls with a province ``geo_code`` return ``None`` because the seat (class) is not
    encoded in the province code; pass a seat code such as ``'NB-1'`` to get ``'SEN-NB-1'``.
    """
    if poll_type == "national_president":
        return "PRES"
    if poll_type == "province_president":
        return f"PRES-{geo_code}"
    if poll_type == "house_district":
        return f"HOUSE-{geo_code}"
    if poll_type == "governor":
        return f"GOV-{geo_code}"
    if poll_type == "senate" and "-" in geo_code:
        return f"SEN-{geo_code}"
    return None


def poll_group_for_race(race_code: str) -> tuple[str, str] | None:
    """Inverse of :func:`race_code_for`: the ``(poll_type, geo_code)`` group polling a race.

    >>> poll_group_for_race("HOUSE-NB-07")
    ('house_district', 'NB-07')
    >>> poll_group_for_race("SEN-NB-1")
    ('senate', 'NB')
    """
    if race_code == "PRES":
        return ("national_president", NATIONAL_GEO)
    prefix, _, rest = race_code.partition("-")
    if not rest:
        return None
    if prefix == "PRES":
        return ("province_president", rest)
    if prefix == "HOUSE":
        return ("house_district", rest)
    if prefix == "SEN":
        return ("senate", rest.split("-")[0])
    if prefix == "GOV":
        return ("governor", rest)
    return None


def province_of_geo(geo_code: str | None) -> str | None:
    """Province code of a poll ``geo_code`` (``'NB'`` for ``'NB'``, ``'NB-07'``, ``'NB-1'``)."""
    if not geo_code or geo_code == NATIONAL_GEO:
        return None
    if _PROVINCE_RE.match(geo_code):
        return geo_code
    m = _PROVINCE_PREFIX_RE.match(geo_code)
    return m.group(1) if m else None


def is_province_code(geo_code: str | None) -> bool:
    """True for two-letter province codes (``'NB'``) other than the national code."""
    return bool(geo_code) and geo_code != NATIONAL_GEO and bool(_PROVINCE_RE.match(str(geo_code)))


def spec_poll_counts(spec: object) -> dict[str, int]:
    """Poll counts per poll type from a :class:`~app.scenarios.schema.PollingSpec` or a mapping.

    A mapping is taken as ``{poll_type: count}`` directly (unknown poll types are rejected).
    """
    if isinstance(spec, Mapping):
        unknown = [k for k in spec if k not in POLL_TYPES]
        if unknown:
            raise ValueError(f"unknown poll types in counts: {unknown}")
        return {str(k): max(0, int(v)) for k, v in spec.items()}
    return {pt: max(0, int(getattr(spec, fld, 0) or 0)) for pt, fld in SPEC_COUNT_FIELDS.items()}


def pollster_attr(p: PollsterLike, name: str, default: object) -> object:
    """Optional attribute of a pollster-like object with a default."""
    value = getattr(p, name, default)
    return default if value is None else value


def pollster_names(pollsters: Sequence[PollsterLike]) -> list[str]:
    """Names of ``pollsters`` (raises on duplicates)."""
    names = [p.name for p in pollsters]
    if len(set(names)) != len(names):
        raise ValueError("duplicate pollster names")
    return names


def lookup_method(method: object, table: Mapping[str, float], default: float) -> float:
    """Value for a survey ``method`` from ``table``, tolerant of free-text labels.

    Exact (case-insensitive) match first, then the longest table key contained in the label, so
    ``"IVR"`` → ``ivr``, ``"probability panel"`` → ``panel``, ``"online opt-in"`` → ``online``.
    """
    label = str(method or "").strip().lower()
    lowered = {str(k).lower(): float(v) for k, v in table.items()}
    if label in lowered:
        return lowered[label]
    for key in sorted(lowered, key=lambda k: (-len(k), k)):
        if key and key in label:
            return lowered[key]
    return float(default)
